# Generated by Django 5.2.6 on 2025-10-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_method',
            field=models.CharField(blank=True, choices=[('local', 'Local'), ('google', 'Google'), ('facebook', 'Facebook'), ('twitter', 'Twitter')], max_length=20),
        ),
    ]
